---
title: Table.FuzzyGroup
---

# Table.FuzzyGroup


Кестедегі жолдарды кілттердің анық емес сәйкестігі негізінде топтайды.


## Syntax

```powerquery
Table.FuzzyGroup(
    table as table,
    key as any,
    aggregatedColumns as list,
    optional options as record
) as table
```


## Remarks

`table` жолдарын әр жол үшін `key` көрсетілген бағанындағы мәндерді анық емес сәйкестендіру арқылы топтайды. Әр топ үшін `aggregatedColumns` арқылы көрсетілген кез келген жинақталған бағандармен бірге кілт бағандарынан (және олардың мәндерінен) тұратын жазба құрылады. Бұл функция жолдардың белгіленген ретін қайтаруға кепілдік бере алмайды.

Кілт бағандарын салыстыру жолын көрсету үшін `options` қосымша жиынтығын қосуға болады. Параметрлерге мыналар кіреді:

-   `Culture` : Жазбаларды тіл және аймаққа тән ережелер негізінде топтауға мүмкіндік береді. Ол кез келген жарамды тіл және аймақтық параметр атауы бола алады. Мысалы, "ja-JP" тіл және аймақтық параметрі жазбаларды жапон тілі және аймақтық параметрлері негізінде топтайды. Әдепкі мәні инвариант ағылшын тілі және аймақтық параметрлері негізінде топтайтын "" болып табылады.
-   `IgnoreCase` : Логикалық (шын/жалған) мән регистрді ескермейтін кілтті топтауға мүмкіндік береді. Мысалы, шын болғанда, "Жүзім" мәні "жүзім" деп топталады. Әдепкі мәні - шын.
-   `IgnoreSpace` : Логикалық (шын/жалған) мән топтарды табу үшін мәтін бөліктерін біріктіруге мүмкіндік береді. Мысалы, шын болғанда, "Жү зім" мәні "Жүзім" деп топталады. Әдепкі мәні - шын.
-   `SimilarityColumnName` : Кіріс мәні мен сол кірісті көрсететін мән арасындағы ұқсастықты көрсететін баған атауы. Әдепкі мәні бос болады, бұл жағдайда ұқсастықтар үшін жаңа баған қосылмайды.
-   `Threshold` : 0,00 және 1,00 аралығындағы сан екі мән топталатын ұқсастық мәнін көрсетеді. Мысалы, "Жүзім" және "Жүім" ("з" әрпі жоқ) осы параметр 0,90 мәнінен аз болса ғана бірге топталады. 1,00 шегі дәл сәйкестіктерге ғана рұқсат етеді. (Нақты емес "дәл сәйкестік" регистр, сөздер тәртібі және тыныс белгілері сияқты айырмашылықтарды елемеуі мүмкін екенін ескеріңіз.) Әдепкі мәні: 0,80.
-   `TransformationTable` : Жазбаларды реттелетін мәнді салыстыру негізінде топтауға мүмкіндік беретін кесте. Онда "Қайдан" және "Қайдан" бағандары болуы керек. Мысалы, түрлендіру кестесінде "Жүзім" мәні бар "Қайдан" бағаны және "Мейіздер" мәні бар "Қайда" бағаны болса, "Жүзім" "Мейіздер" мәнімен топталады. Түрлендіру түрлендіру кестесіндегі мәтіннің барлық нұсқаларына қолданылатынын ескеріңіз. Жоғарыдағы түрлендіру кестесінде "Жүзім тәтті" мәні сонымен қатар "Мейіздер тәтті" деп топталады.


## Examples

### Example #1
Әр орындағы (`әр Table.RowCount(_)`) қызметкерлер саны бар жиынтық баған \[Count\] қосу арқылы кестелерді топтаңыз.
```powerquery
Table.FuzzyGroup(
    Table.FromRecords(
        {
            [EmployeeID = 1, Location = "Seattle"],
            [EmployeeID = 2, Location = "seattl"],
            [EmployeeID = 3, Location = "Vancouver"],
            [EmployeeID = 4, Location = "Seatle"],
            [EmployeeID = 5, Location = "vancover"],
            [EmployeeID = 6, Location = "Seattle"],
            [EmployeeID = 7, Location = "Vancouver"]
        },
        type table [EmployeeID = nullable number, Location = nullable text]
    ),
    "Location",
    {"Count", each Table.RowCount(_)},
    [IgnoreCase = true, IgnoreSpace = true]
)
```

Result: 
```powerquery
Table.FromRecords({
    [Location = "Seattle", Count = 4],
    [Location = "Vancouver", Count = 3]
})
```




## Category
Table.Transformation
