---
title: Table.View
---

# Table.View


Кестені жасайды немесе оны сұрау және әрекет операциялары үшін пайдаланушы анықтайтын өңдегіштермен кеңейтеді.


## Syntax

```powerquery
Table.View(
    table as table,
    handlers as record
) as table
```


## Remarks

Операция көрініске қолданылатын кезде, `table` көрсетілген функциялар операцияның әдепкі орындалу ретінің орнына пайдаланылатын `handlers` көрінісін қайтарады.

Егер `table` көрсетілген болса, барлық өңдегіш функциялары міндетті емес болып табылады. Егер `table` көрсетілмесе, `GetType` және `GetRows` өңдегіш функциялары міндетті болады. Егер операция үшін өңдегіш функциясы көрсетілмесе, `table` үшін операцияның әдепкі орындалу реті қолданылады (`GetExpression` жағдайынан басқа).

Өңдегіш функциялары `table` үшін қолданылған операцияның нәтижесіне семантикалық эквивалентті мәнді қайтаруы тиіс (немесе `GetExpression` жағдайындағы алынатын көріністі).

Егер өңдегіш функциясы қате шығарса, көрініске операцияның әдепкі орындалу реті қолданылады.

`Table.View` — M сұрауларын дереккөзге сәйенс сұрауларға түрлендіру (мысалы, M сұрауларынан T-SQL нұсқауларын жасау).

`Table.View` туралы толығырақ сипаттама алу үшін жарияланған Power Query реттелмелі қосқыш құжаттарын қараңыз.


## Examples

### Example #1
Жолдардың түрін немесе санын анықтау үшін жолға қатынасу рұқсатын қажет етпейтін негізгі көріністі жасаңыз.
```powerquery
Table.View(
    null,
    [
        GetType = () => type table [CustomerID = number, Name = text, Phone = nullable text],
        GetRows = () => Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
        GetRowCount = () => 1
    ]
)
```

Result: 
```powerquery
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```




## Category
Table.Table construction
