---
title: Table.FuzzyJoin
---

# Table.FuzzyJoin


Көрсетілген кілттерге негізделіп анық емес сәйкес екі кестенің жолдарын біріктіреді.


## Syntax

```powerquery
Table.FuzzyJoin(
    table1 as table,
    key1 as any,
    table2 as table,
    key2 as any,
    optional joinKind as JoinKind.Type,
    optional joinOptions as record
) as table
```


## Remarks

`table1` жолдарын `key1` (`table1` үшін) және `key2` (`table2` үшін) арқылы таңдалған кілт бағандарының мәндерін анық емес сәйкестендіру негізінде `table2` жолдарымен қосылады.

Анық емес сәйкестендіру - бұл мәтіннің теңдігіне емес, мәтіннің ұқсастығына негізделген салыстыру.

Әдепкі бойынша ішкі біріктіру орындалады, алайда қосымша `joinKind` қосылу түрін көрсету үшін қосылуы мүмкін. Параметрлерге мыналар кіреді:

-   `JoinKind.Inner`
-   `JoinKind.LeftOuter`
-   `JoinKind.RightOuter`
-   `JoinKind.FullOuter`
-   `JoinKind.LeftAnti`
-   `JoinKind.RightAnti`
-   `JoinKind.LeftSemi`
-   `JoinKind.RightSemi`

Кілт бағандарын салыстыру жолын көрсету үшін `joinOptions` қосымша жиынтығын қосуға болады. Параметрлерге мыналар кіреді:

-   `ConcurrentRequests` : 1 мен 8 бар арасындағы сан анық емес сәйкестік үшін пайдаланылатын параллель ағындар санын көрсетеді. Әдепкі мән — 1.
-   `Culture` : Жазбаларды тіл және аймаққа тән ережелер негізінде сәйкестендіруге мүмкіндік береді. Ол кез келген жарамды тіл және аймақтық параметр атауы бола алады. Мысалы, "ja-JP" тіл және аймақтық параметрі жазбаларды жапон тілі және аймақтық параметрлері негізінде сәйкестендіреді. Әдепкі мәні инвариант ағылшын тілі және аймақтық параметрлері негізінде сәйкестендіретін "" болып табылады.
-   `IgnoreCase` : Логикалық (шын/жалған) мән регистрді ескермейтін кілтті сәйкестендіруге мүмкіндік береді. Мысалы, шын болғанда, "Жүзім" мәні "жүзім" деп сәйкестендіріледі. Әдепкі мәні - шын.
-   `IgnoreSpace` : Логикалық (шын/жалған) мән сәйкестіктерді табу үшін мәтін бөліктерін біріктіруге мүмкіндік береді. Мысалы, шын болғанда, "Жү зім" мәні "Жүзім" деп сәйкестендіріледі. Әдепкі мәні - шын.
-   `NumberOfMatches` : Әрбір кіріс жолы үшін қайтаруға болатын сәйкес жолдардың максимал санын көрсететін бүтін сан. Мысалы, 1 мәні әрбір кіріс жолы үшін ең көбі бір сәйкес жолды қайтарады. Егер бұл параметр берілмесе, барлық сәйкес жолдар қайтарылады.
-   `SimilarityColumnName` : Кіріс мәні мен сол кірісті көрсететін мән арасындағы ұқсастықты көрсететін баған атауы. Әдепкі мәні бос болады, бұл жағдайда ұқсастықтар үшін жаңа баған қосылмайды.
-   `Threshold` : 0,00 және 1,00 аралығындағы сан екі мән сәйкестендірілетін ұқсастық мәнін көрсетеді. Мысалы, "Жүзім" және "Жүім" ("з" әрпі жоқ) осы параметр 0,90 мәнінен аз болса ғана сәйкестендіріледі. 1,00 шегі дәл сәйкестіктерге ғана рұқсат етеді. (Нақты емес "дәл сәйкестік" регистр, сөздер тәртібі және тыныс белгілері сияқты айырмашылықтарды елемеуі мүмкін екенін ескеріңіз.) Әдепкі мәні: 0,80.
-   `TransformationTable` : Жазбаларды реттелетін мәнді салыстыру негізінде сәйкестендіруге мүмкіндік беретін кесте. Онда "Қайдан" және "Қайдан" бағандары болуы керек. Мысалы, түрлендіру кестесінде "Жүзім" мәні бар "Қайдан" бағаны және "Мейіздер" мәні бар "Қайда" бағаны болса, "Жүзім" "Мейіздер" мәнімен сәйкестендіріледі. Түрлендіру түрлендіру кестесіндегі мәтіннің барлық нұсқаларына қолданылатынын ескеріңіз. Жоғарыдағы түрлендіру кестесінде "Жүзім тәтті" мәні сонымен қатар "Мейіздер тәтті" деп сәйкестендіріледі.


## Examples

### Example #1
\[FirstName\] негізіндегі екі кестені сол жақ ішкі анық емес біріктіру
```powerquery
Table.FuzzyJoin(
    Table.FromRecords(
        {
            [CustomerID = 1, FirstName1 = "Bob", Phone = "555-1234"],
            [CustomerID = 2, FirstName1 = "Robert", Phone = "555-4567"]
        },
        type table [CustomerID = nullable number, FirstName1 = nullable text, Phone = nullable text]
    ),
    {"FirstName1"},
    Table.FromRecords(
        {
            [CustomerStateID = 1, FirstName2 = "Bob", State = "TX"],
            [CustomerStateID = 2, FirstName2 = "bOB", State = "CA"]
        },
        type table [CustomerStateID = nullable number, FirstName2 = nullable text, State = nullable text]
    ),
    {"FirstName2"},
    JoinKind.LeftOuter,
    [IgnoreCase = true, IgnoreSpace = false]
)
```

Result: 
```powerquery
Table.FromRecords({
    [
        CustomerID = 1,
        FirstName1 = "Bob",
        Phone = "555-1234",
        CustomerStateID = 1,
        FirstName2 = "Bob",
        State = "TX"
    ],
    [
        CustomerID = 1,
        FirstName1 = "Bob",
        Phone = "555-1234",
        CustomerStateID = 2,
        FirstName2 = "bOB",
        State = "CA"
    ],
    [
        CustomerID = 2,
        FirstName1 = "Robert",
        Phone = "555-4567",
        CustomerStateID = null,
        FirstName2 = null,
        State = null
    ]
})
```




## Category
Table.Transformation
