---
title: Table.Distinct
---

# Table.Distinct


तालिका से डुप्लिकेट पंक्तियाँ निकालता है.


## Syntax

```powerquery
Table.Distinct(
    table as table,
    optional equationCriteria as any
) as table
```


## Remarks

यह तालिका से डुप्लिकेट पंक्तियाँ हटाता है. एक वैकल्पिक पैरामीटर, `equationCriteria`, यह निर्दिष्ट करता है कि तालिका के किन कॉलम की डुप्लीकेशन के लिए जाँच की जाएगी. अगर `equationCriteria` निर्दिष्ट नहीं है, तो सभी कॉलम का परीक्षण किया जाता है.  
  
क्योंकि Power Query कभी-कभी कुछ ऑपरेशन्स को बैकएंड डेटा स्रोतों पर ऑफ़लोड कर देता है (जिसे "फोल्डिंग" कहा जाता है), और कभी-कभी द्वारा क्वेरीज़ को ऑप्टिमाइज़ भी करता है उन ऑपरेशन्स को छोड़ते हुए जो पूरी तरह से ज़रूरी नहीं हैं, आम तौर पर इस बात की कोई गारंटी नहीं होती कि कौन-सा विशिष्ट डुप्लीकेट बचा रहेगा. उदाहरण के लिए, आप यह नहीं मान सकते कि कॉलम मानों के एक अद्वितीय सेट वाली पहली पंक्ति बनी रहेगी, और तालिका में नीचे की ओर वाली पंक्तियाँ हटा दी जाएँगी. अगर आप चाहते हैं कि डुप्लीकेट हटाने की प्रक्रिया अनुमानित तरीके से काम करे, तो सबसे पहले `Table.Buffer` का उपयोग करके तालिका को बफ़र करें.


## Examples

### Example #1
तालिका से डुप्लिकेट पंक्तियाँ निकालें.
```powerquery
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "b"],
        [a = "A", b = "a"]
    })
)
```

Result: 
```powerquery
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "B", b = "b"]
})
```


### Example #2
तालिका `({[a = "A", b = "a"], [a = "B", b = "a"], [a = "A", b = "b"]})` में मौजूद स्तंभ \[b\] से डुप्लिकेट पंक्तियाँ निकालें.
```powerquery
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "a"],
        [a = "A", b = "b"]
    }),
    "b"
)
```

Result: 
```powerquery
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "A", b = "b"]
})
```




## Category
Table.Membership
