---
title: Table.Pivot
---

# Table.Pivot


Öznitelik değer çiftlerini temsil eden sütun çiftleri ile öznitelik sütunundaki verileri bir sütun başlığı olarak döndürür.


## Syntax

```powerquery
Table.Pivot(
    table as table,
    pivotValues as list,
    attributeColumn as text,
    valueColumn as text,
    optional aggregationFunction as function
) as table
```


## Remarks

Öznitelik değer çiftlerini temsil eden sütun çiftleri ile öznitelik sütunundaki verileri bir sütun başlığı olarak döndürür.


## Examples

### Example #1
`({ [ key = "x", attribute = "a", value = 1 ], [ key = "x", attribute = "c", value = 3 ], [ key = "y", attribute = "a", value = 2 ], [ key = "y", attribute = "b", value = 4 ] })` tablosundaki öznitelik sütunundaki "a", "b" ve "c" değerlerini alır ve kendi sütunlarına özetler.
```powerquery
Table.Pivot(
    Table.FromRecords({
        [key = "x", attribute = "a", value = 1],
        [key = "x", attribute = "c", value = 3],
        [key = "y", attribute = "a", value = 2],
        [key = "y", attribute = "b", value = 4]
    }),
    {"a", "b", "c"},
    "attribute",
    "value"
)
```

Result: 
```powerquery
Table.FromRecords({
    [key = "x", a = 1, b = null, c = 3],
    [key = "y", a = 2, b = 4, c = null]
})
```


### Example #2
`({ [ key = "x", attribute = "a", value = 1 ], [ key = "x", attribute = "c", value = 3 ], [ key = "x", attribute = "c", value = 5 ], [ key = "y", attribute = "a", value = 2 ], [ key = "y", attribute = "b", value = 4 ] })` tablosundaki öznitelik sütunundaki "a", "b" ve "c" değerlerini alır ve kendi sütunlarına özetler. "x" anahtarına ait "c" özniteliği kendisi ile ilişkili birden çok değer içeriyor, bu nedenle çakışmayı gidermek için List.Max işlevini kullanın.
```powerquery
Table.Pivot(
    Table.FromRecords({
        [key = "x", attribute = "a", value = 1],
        [key = "x", attribute = "c", value = 3],
        [key = "x", attribute = "c", value = 5],
        [key = "y", attribute = "a", value = 2],
        [key = "y", attribute = "b", value = 4]
    }),
    {"a", "b", "c"},
    "attribute",
    "value",
    List.Max
)
```

Result: 
```powerquery
Table.FromRecords({
    [key = "x", a = 1, b = null, c = 5],
    [key = "y", a = 2, b = 4, c = null]
})
```




## Category
Table.Column operations
