---
title: Table.View
---

# Table.View


Создает или расширяет таблицу, используя определенные пользователем обработчики операций запросов и действий.


## Syntax

```powerquery
Table.View(
    table as table,
    handlers as record
) as table
```


## Remarks

Возвращает представление `table`, применяемые к которому операции действуют не по умолчанию, а используя функции-обработчики, указанные в `handlers`.

В случае указания `table` задавать какие-либо функции-обработчики не обязательно. Если же не указывать `table`, обязательно необходимы функции-обработчики `GetType` и `GetRows`. Если не указать для операции функцию-обработчик, вместо нее операция (если это не `GetExpression`) применяет к `table` свои действия по умолчанию.

Функции-обработчики должны возвращать значение, семантически эквивалентное результату применения операции к `table` (или к результирующему представлению для `GetExpression`).

Если функция-обработчик выдает ошибку, к представлению применяются действия операции по умолчанию.

`Table.View` позволяет реализовать для источника данных свертывание — перевод запросов M в запросы конкретного источника (например, создание инструкций T-SQL из запросов M).

Более полное описание `Table.View` см. в опубликованной документации по настраиваемым соединителям Power Query.


## Examples

### Example #1
Создайте базовое представление, которое не требует доступа к строкам для определения типа или количества строк.
```powerquery
Table.View(
    null,
    [
        GetType = () => type table [CustomerID = number, Name = text, Phone = nullable text],
        GetRows = () => Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
        GetRowCount = () => 1
    ]
)
```

Result: 
```powerquery
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```




## Category
Table.Table construction
