---
title: Table.FuzzyGroup
---

# Table.FuzzyGroup


Группирует строки таблицы на основе нечеткого соответствия ключей.


## Syntax

```powerquery
Table.FuzzyGroup(
    table as table,
    key as any,
    aggregatedColumns as list,
    optional options as record
) as table
```


## Remarks

Группирует строки <code>table</code> по нечеткому соответствию значений в заданном столбце <code>key</code> для каждой строки.    Для каждой группы создается запись, содержащая ключевые столбцы (и их значения), а также агрегированные столбцы, указываемые в <code>aggregatedColumns</code>.    Эта функция не может гарантировать возврат строк в фиксированном порядке.    Возможно указание необязательного набора параметров <code>options</code>, задающих принцип сравнения ключевых столбцов. Допустимы следующие параметры:    <ul><li><code>Culture</code> : Позволяет группировать записи на основе правил конкретного языка и региональных параметров. Например, параметр Culture со значением &quot;ja-JP&quot; группирует записи согласно правилам японского языка. Значение по умолчанию&#160;— &quot;&quot;, при котором используется инвариантный английский язык и региональные параметры.</li><li><code>IgnoreCase</code> : Логическое значение (true/false), которое разрешает группирование ключей без учета регистра. Например, когда задано true, &quot;Виноград&quot; будет группироваться с &quot;виноград&quot;. Значение по умолчанию&#160;— true.</li><li><code>IgnoreSpace</code> : Логическое значение (true/false), которое разрешает объединять части текста для поиска групп. Например, когда задано true, &quot;Вино град&quot; будет группироваться с &quot;Виноград&quot;. Значение по умолчанию&#160;— true.</li><li><code>SimilarityColumnName</code> : Имя столбца, в котором показано сходство входного значения и репрезентативного значения для этих входных данных. Значение по умолчанию&#160;— NULL. В этом случае новый столбец для сходства не будет добавлен.</li><li><code>Threshold</code> : Число от 0,00 до 1,00, указывающее показатель подобия, при котором два значения объединяются в одну группу.    Например, &quot;Виноград&quot; и &quot;Виногрд&quot; (без буквы &quot;а&quot;) группируются вместе, только если задано значение этого параметра ниже 0,90.    Порог в 1,00 позволяет исключительно точные совпадения.     (Обратите внимание, что нечеткое &quot;точное совпадение&quot; может игнорировать такие различия, как регистр, порядок слов и пунктуация.)    Значение по умолчанию — 0,80.</li><li><code>TransformationTable</code> : Таблица, позволяющая группировать записи по настраиваемым сопоставлениям значений. Она должна содержать столбцы From (от чего) и To (к чему). Например, если таблица преобразования содержит в столбце From значение &quot;Виноград&quot;, а в столбце To значение &quot;Изюм&quot;, то эти два значения будут группироваться вместе. Преобразование будет применяться ко всем вхождениям текста, указанного в таблице. Согласно таблице выше, &quot;Виноград сладкий&quot; будет также группироваться с &quot;Изюм сладкий&quot;.</li></ul><br />    


## Examples

### Example #1 
Группирование таблицы с добавлением агрегатного столбца [Count], который содержит число сотрудников в каждом расположении (&#34;each Table.RowCount(_))&#34;).
```powerquery
Table.FuzzyGroup(
    Table.FromRecords(
        {
            [EmployeeID = 1, Location = "Seattle"],
            [EmployeeID = 2, Location = "seattl"],
            [EmployeeID = 3, Location = "Vancouver"],
            [EmployeeID = 4, Location = "Seatle"],
            [EmployeeID = 5, Location = "vancover"],
            [EmployeeID = 6, Location = "Seattle"],
            [EmployeeID = 7, Location = "Vancouver"]
        },
        type table [EmployeeID = nullable number, Location = nullable text]
    ),
    "Location",
    {"Count", each Table.RowCount(_)},
    [IgnoreCase = true, IgnoreSpace = true]
)
```

Result: 
```powerquery
Table.FromRecords({
    [Location = "Seattle", Count = 4],
    [Location = "Vancouver", Count = 3]
})
```




## Category
Table.Transformation
