---
title: Table.Unpivot
---

# Table.Unpivot


## Description

Změní sadu sloupců v tabulce na páry atribut-hodnota.


## Syntax

```powerquery
Table.Unpivot(
    table as table,
    pivotColumns as list,
    attributeColumn as text,
    valueColumn as text
) as table
```


## Details

Změní sadu sloupců v tabulce na páry atribut-hodnota kombinované se zbytkem hodnot v jednotlivých řádcích.


## Examples

### Example #1 
Vezme sloupce „a“, „b“ a „c“ tabulky &lt;code&gt;(\{[ key = &#34;x&#34;, a = 1, b = null, c = 3 ], [ key = &#34;y&#34;, a = 2, b = 4, c = null ]})&lt;/code&gt; a převedením na řádky je změní na páry atribut-hodnota.
```powerquery
Table.Unpivot(
    Table.FromRecords({
        [key = "x", a = 1, b = null, c = 3],
        [key = "y", a = 2, b = 4, c = null]
    }),
    {"a", "b", "c"},
    "attribute",
    "value"
)
```

Result: 
```powerquery
Table.FromRecords({
    [key = "x", attribute = "a", value = 1],
    [key = "x", attribute = "c", value = 3],
    [key = "y", attribute = "a", value = 2],
    [key = "y", attribute = "b", value = 4]
})
```




## Category
Table.Column operations
