---
title: Table.MaxN
---

# Table.MaxN


Повертає найбільші рядки за даним критерієм.


## Syntax

```powerquery
Table.MaxN(
    table as table,
    comparisonCriteria as any,
    countOrCondition as any
) as table
```


## Remarks

Повертає найбільші рядки в таблиці (`table`) за такої умови: `comparisonCriteria`. Після сортування рядків необхідно вказати значення параметра `countOrCondition`, щоб забезпечити подальше фільтрування результату. Зверніть увагу: алгоритм сортування не може забезпечувати постійно однаковий результат сортування. Параметр `countOrCondition` може мати кілька форм.

-   Якщо вказано число, функція повертає список з упорядкованими за зростанням елементами кількістю до `countOrCondition`.
-   Якщо вказано умову, функція повертає список елементів, які спочатку відповідають цій умові. Щойно виявиться невідповідність елемента умові, наступні елементи не розглядаються.


## Examples

### Example #1
Знайти в таблиці рядок із найбільшим значенням у стовпці \[a\] за умови, що \[a\] > 0. Рядки сортуються перед застосуванням фільтра.
```powerquery
Table.MaxN(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 0, b = 0],
        [a = 6, b = 2]
    }),
    "a",
    each [a] > 0
)
```

Result: 
```powerquery
Table.FromRecords({
    [a = 6, b = 2],
    [a = 2, b = 4]
})
```


### Example #2
Знайти в таблиці рядок із найбільшим значенням у стовпці \[a\] за умови, що \[b\] > 0. Рядки сортуються перед застосуванням фільтра.
```powerquery
Table.MaxN(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 8, b = 0],
        [a = 6, b = 2]
    }),
    "a",
    each [b] > 0
)
```

Result: 
```powerquery
Table.FromRecords({})
```




## Category
Table.Ordering
