---
title: Table.View
---

# Table.View


Створює або розширює таблицю з користувацькими обробниками для операцій запитів і дій.


## Syntax

```powerquery
Table.View(
    table as table,
    handlers as record
) as table
```


## Remarks

Повертає подання таблиці "`table`", де функції, визначені параметром `handlers`, використовуються замість поведінки за замовчуванням, коли до цього подання застосовують певну операцію.

Якщо `table` указано, усі функції обробника є необов’язковими. Якщо `table` не вказано, функції обробника `GetType` і `GetRows` необхідно вказати. Якщо для операції не вказано функцію обробника, до таблиці "`table`" натомість застосовується поведінка за замовчуванням для цієї операції (окрім випадків застосування функції `GetExpression`).

Функції обробника мають повертати значення, семантично еквівалентне результату виконання операції для таблиці "`table`" (або отримане подання, якщо використовується `GetExpression`).

Якщо функція обробника повертає помилку, до подання застосовується поведінка за замовчуванням для цієї операції.

Можна використати `Table.View`, щоб запровадити складання до джерела даних – перетворити запити M на запити для конкретних джерел (наприклад, створити інструкцію T-SQL для запитів M).

Перегляньте опубліковану документацію щодо настроюваного з’єднувача Power Query, щоб дізнатися більше про `Table.View`.


## Examples

### Example #1
Створіть просте подання, яке не потребує доступу до рядків для визначення типу або кількості рядків.
```powerquery
Table.View(
    null,
    [
        GetType = () => type table [CustomerID = number, Name = text, Phone = nullable text],
        GetRows = () => Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
        GetRowCount = () => 1
    ]
)
```

Result: 
```powerquery
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```




## Category
Table.Table construction
