---
title: Table.Partition
---

# Table.Partition


Διαμερίζει τον πίνακα σε μια λίστα πινάκων με βάση τον αριθμό των καθορισμένων ομάδων και στηλών.


## Syntax

```powerquery
Table.Partition(
    table as table,
    column as text,
    groups as number,
    hash as function
) as list
```


## Remarks

Διαμερίζει τον `table` σε μια λίστα `groups` πινάκων, με βάση την τιμή της `column` και μιας συνάρτησης `hash`. Η συνάρτηση `hash` εφαρμόζεται στην τιμή της γραμμής `column` για να λάβει μια τιμή κατακερματισμού για τη γραμμή. Το υπόλοιπο της τιμής κατακερματισμού `groups` προσδιορίζει σε ποιον από τους επιστρεφόμενους πίνακες θα τοποθετηθεί η γραμμή.

-   `table`: Ο πίνακας για διαμέριση.
-   `column`: Η στήλη κατακερματισμού για προσδιορισμό του επιστρεφόμενου πίνακα στον οποίο βρίσκεται η γραμμή.
-   `groups`: Ο αριθμός των πινάκων στους οποίους θα διαμεριστεί ο πίνακας εισόδου.
-   `hash`: Η συνάρτηση που εφαρμόζεται για να ληφθεί μια τιμή κατακερματισμού.


## Examples

### Example #1
Διαμερίστε τον πίνακα `({[a = 2, b = 4], [a = 6, b = 8], [a = 2, b = 4], [a = 1, b = 4]})` σε 2 πίνακες στη στήλη \[a\], χρησιμοποιώντας την τιμή των στηλών ως συνάρτηση κατακερματισμού.
```powerquery
Table.Partition(
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 1, b = 4],
        [a = 2, b = 4],
        [a = 1, b = 4]
    }),
    "a",
    2,
    each _
)
```

Result: 
```powerquery
{
    Table.FromRecords({
        [a = 2, b = 4],
        [a = 2, b = 4]
    }),
    Table.FromRecords({
        [a = 1, b = 4],
        [a = 1, b = 4]
    })
}
```




## Category
Table.Row operations
