---
title: Table.View
---

# Table.View


## Description

Δημιουργεί ή επεκτείνει έναν πίνακα με δείκτες χειρισμού καθορισμένους από το χρήστη για λειτουργίες ερωτήματος και ενέργειας.


## Syntax

```powerquery
Table.View(
    table as table,
    handlers as record
) as table
```


## Details

Επιστρέφει μια προβολή του <code>table</code> όπου οι συναρτήσεις που καθορίζονται στο <code>handlers</code> χρησιμοποιούνται αντί της προεπιλεγμένης συμπεριφοράς μιας λειτουργίας όταν η λειτουργία εφαρμόζεται στην προβολή.<br />Αν <code>table</code> παρέχεται, όλες οι λειτουργίες χειριστή είναι προαιρετικές. Αν <code>table</code> δεν παρέχεται, απαιτούνται οι λειτουργίες χειριστή <code>GetType</code> και <code>GetRows</code>. Αν μια συνάρτηση χειριστή δεν έχει καθοριστεί για μια λειτουργία, η προεπιλεγμένη συμπεριφορά της λειτουργίας εφαρμόζεται στο <code>table</code> (εκτός από την περίπτωση του <code>GetExpression</code>).<br />Οι συναρτήσεις του Handler πρέπει να επιστρέψουν ένα τιμή που είναι σημασιολογικά ισοδύναμη με το αποτέλεσμα της εφαρμογής της λειτουργίας έναντι του <code>table</code> (ή της προκύπτουσας προβολής στην περίπτωση του <code>GetExpression</code>).<br />Αν μια συνάρτηση χειριστή εμφανίσει σφάλμα, η προεπιλεγμένη συμπεριφορά της λειτουργίας εφαρμόζεται στην προβολή.<br /><code>Table.View</code> μπορεί να χρησιμοποιηθεί για την εφαρμογή αναδίπλωσης σε μια πηγή δεδομένων – η μετάφραση των ερωτημάτων M σε ερωτήματα για συγκεκριμένη πηγή (για παράδειγμα, για να δημιουργήσετε δηλώσεις T-SQL από ερωτήματα M).<br />Ανατρέξτε στη δημοσιευμένη τεκμηρίωση προσαρμοσμένης σύνδεσης Power Query για μια πιο ολοκληρωμένη περιγραφή του <code>Table.View</code>.<br />


## Examples

### Example #1 
Δημιουργήστε μια βασική προβολή που δεν απαιτεί πρόσβαση στις γραμμές για τον προσδιορισμό του τύπου ή του πλήθους γραμμών.
```powerquery
Table.View(
    null,
    [
        GetType = () => type table [CustomerID = number, Name = text, Phone = nullable text],
        GetRows = () => Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]}),
        GetRowCount = () => 1
    ]
)
```

Result: 
```powerquery
Table.FromRecords({[CustomerID = 1, Name = "Bob", Phone = "123-4567"]})
```




## Category
Table.Table construction
