---
title: Table.Distinct
---

# Table.Distinct


## Description

Καταργεί τις διπλότυπες γραμμές από τον πίνακα.


## Syntax

```powerquery
Table.Distinct(
    table as table,
    optional equationCriteria as any
) as table
```


## Details

Καταργεί τις διπλότυπες σειρές από τον πίνακα.    Μια προαιρετική παράμετρος, <code>equationCriteria</code>, καθορίζει ποιες στήλες του πίνακα ελέγχονται για διπλασιασμό. Εάν δεν έχει καθοριστεί το <code>equationCriteria</code>, ελέγχονται όλες οι στήλες.<br />    <br />    Επειδή το Power Query μερικές φορές εκφορτώνει ορισμένες λειτουργίες σε πηγές δεδομένων υποστήριξης (γνωστές ως "αναδίπλωση"), και, επίσης, μερικές φορές βελτιστοποιεί ερωτήματα     παρακάμπτοντας λειτουργίες που δεν είναι αυστηρά απαραίτητες, γενικά δεν υπάρχει καμία εγγύηση για το συγκεκριμένο αντίγραφο θα διατηρηθεί.    Για παράδειγμα, δεν μπορείτε να υποθέσετε ότι το πρώτο αντίγραφο θα διατηρηθεί. Η σειρά με ένα μοναδικό σύνολο τιμών στηλών θα παραμείνει και οι σειρές πιο κάτω στον πίνακα θα αφαιρεθούν.    Εάν θέλετε η διπλότυπη κατάργηση να συμπεριφέρεται προβλέψιμα, αποθηκεύστε πρώτα τον πίνακα χρησιμοποιώντας το <code>Table.Buffer</code>.


## Examples

### Example #1 
Καταργεί όλες τις διπλότυπες γραμμές από τον πίνακα.
```powerquery
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "b"],
        [a = "A", b = "a"]
    })
)
```

Result: 
```powerquery
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "B", b = "b"]
})
```


### Example #2 
Καταργήστε όλες τις διπλότυπες γραμμές από τη στήλη [b] του πίνακα &lt;code&gt;(\{[a = &#34;A&#34;, b = &#34;a&#34;], [a = &#34;B&#34;, b = &#34;a&#34;], [a = &#34;A&#34;, b = &#34;b&#34;]})&lt;/code&gt;.
```powerquery
Table.Distinct(
    Table.FromRecords({
        [a = "A", b = "a"],
        [a = "B", b = "a"],
        [a = "A", b = "b"]
    }),
    "b"
)
```

Result: 
```powerquery
Table.FromRecords({
    [a = "A", b = "a"],
    [a = "A", b = "b"]
})
```




## Category
Table.Membership
