name: Install and Run Power BI Desktop

on: [push]

jobs:
  powerbi-installation:
    runs-on: [ windows-latest] # This needs to be a self-hosted runner with Windows and GUI

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Power BI Desktop
      run: |
        choco install --ignore-checksums powerbi

    - name: Start Power BI Desktop with PBIX
      run: |
        $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "pre-scripts\dox.pbix"
        if (Test-Path $pbixPath) {
          Start-Process "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe" -ArgumentList $pbixPath
          Start-Sleep -Seconds 60
        } else {
          Write-Error "PBIX file not found at path: $pbixPath"
          exit 1
        }

    - name: Get msmdsrv.exe port
      run: |
        $ProcessInfo = Get-Process -Name msmdsrv -ErrorAction SilentlyContinue
        if ($ProcessInfo) {
            $ProcessId = $ProcessInfo.Id
            $NetStatInfo = netstat -ano | Select-String "$ProcessId"
            $Port = $NetStatInfo -replace '.*\:(\d+).*', '$1'
            echo "Power BI Desktop msmdsrv.exe is listening on port: $Port"
            echo "MSMDSRV_PORT=$Port" >> $GITHUB_ENV
        } else {
            echo "msmdsrv.exe process not found."
        }
