name: Install and Run Power BI Desktop

on: [push]

jobs:
  powerbi-installation:
    runs-on: [ windows-latest] # This needs to be a self-hosted runner with Windows and GUI

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Power BI Desktop
      run: |
        choco install --ignore-checksums powerbi

    - name: Start Power BI Desktop
      run: |
        $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "pre-script\dox.pbix"
        # Starts Power BI Desktop. Modify the path if necessary.
        Start-Process "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe" -ArgumentList $pbixPath
        # Wait for a moment to ensure Power BI Desktop starts up
        Start-Sleep -Seconds 30

    - name: Get msmdsrv.exe port
      run: |
        $ProcessInfo = Get-Process -Name msmdsrv -ErrorAction SilentlyContinue
        if ($ProcessInfo) {
            $ProcessId = $ProcessInfo.Id
            $NetStatInfo = netstat -ano | Select-String "$ProcessId"
            $Port = $NetStatInfo -replace '.*\:(\d+).*', '$1'
            echo "Power BI Desktop msmdsrv.exe is listening on port: $Port"
            echo "MSMDSRV_PORT=$Port" >> $GITHUB_ENV
        } else {
            echo "msmdsrv.exe process not found."
        }
