name: Install and Run Power BI Desktop

on: [push]

jobs:
  powerbi-installation:
    runs-on: [ windows-latest] # This needs to be a self-hosted runner with Windows and GUI

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Power BI Desktop
      run: |
        choco install --ignore-checksums powerbi

    - name: Start Power BI Desktop with PBIX
      run: |
        $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "pre-scripts\dox.pbix"
        if (Test-Path $pbixPath) {
          Start-Process "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe" -ArgumentList $pbixPath
          Start-Sleep -Seconds 60
        } else {
          Write-Error "PBIX file not found at path: $pbixPath"
          exit 1
        }

    - name: Get msmdsrv.exe port
      id: get-msmdsrv-port
      run: |
        $msmdsrvPorts = Get-Process -Name msmdsrv -ErrorAction SilentlyContinue | ForEach-Object {
          Get-NetTCPConnection -OwningProcess $_.Id | Select-Object LocalPort -Unique
        }

        if ($msmdsrvPorts) {
          foreach ($port in $msmdsrvPorts) {
            Write-Host "msmdsrv.exe is listening on port: $($port.LocalPort)"
          }
          # Assume there is only one instance for simplicity and set it as an environment variable
          echo "MSMDSRV_PORT=$($msmdsrvPorts[0].LocalPort)" >> $GITHUB_ENV
          echo "::set-output name=msmdsrv-port::$($msmdsrvPorts[0].LocalPort)"
        } else {
          Write-Host "No msmdsrv.exe process found."
        }

    - name: Debug - Print MSMDSRV_PORT
      run: |
        $msmdsrvPort = "${{ steps.get-msmdsrv-port.outputs.msmdsrv-port }}"
        Write-Host "MSMDSRV_PORT value is $msmdsrvPort"

    - name: Process the first database on the instance
      run: |
        Import-Module SqlServer
        $port = "${{ steps.get-msmdsrv-port.outputs.msmdsrv-port }}"
        $asInstance = "localhost:$port"
        $connectionString = "Data Source=localhost:$port;"
        # Invoke the command and expect the result to be in XML format
        $xmlResult = Invoke-ASCmd -ConnectionString $connectionString -Query "SELECT [CATALOG_NAME] FROM $SYSTEM.DBSCHEMA_CATALOGS"
        
        # Parse the XML result
        $xml = [xml]$xmlResult

        # Now extract the data you need from the XML
        # You need to adjust the XPath query according to the actual structure of the XML
        $dbName = $xml.Rowset.Row.CATALOG_NAME

        # Process the database
        Invoke-ASCmd -Server $asInstance -Query "{
          ""refresh"": {
            ""type"": ""full"",
            ""objects"": [
              {
                ""database"": ""$dbName""
              }
            ]
          }
        }"
        
        Start-Sleep -Seconds 60
        
        Write-Host "Database $dbName processed."

    - name: Run DAX query and output the result
      run: |
        Import-Module SqlServer
        $port = "${{ steps.get-msmdsrv-port.outputs.msmdsrv-port }}"
        $asInstance = "localhost:$port"
        
        $daxResult = Invoke-ASCmd -Server $asInstance -Query "EVALUATE enumerations"
        Write-Host "DAX Query Result:"
        Write-Host $daxResult

    - name: Close Power BI Desktop
      run: |
        Stop-Process -Name PBIDesktop -Force -ErrorAction SilentlyContinue
        Write-Host "Power BI Desktop closed."

    - name: Set PQ_UICultureOverride environment variable
      run: |
        [Environment]::SetEnvironmentVariable("PQ_UICultureOverride", "fr-FR", [EnvironmentVariableTarget]::User)
        Write-Host "Environment variable PQ_UICultureOverride set to fr-FR."

    - name: Start Power BI Desktop with PBIX in French
      run: |
        $pbixPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "pre-scripts\dox.pbix"
        if (Test-Path $pbixPath) {
          Start-Process "C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe" -ArgumentList $pbixPath
          Start-Sleep -Seconds 60
        } else {
          Write-Error "PBIX file not found at path: $pbixPath"
          exit 1
        }

    - name: Get msmdsrv.exe port in French
      id: get-msmdsrv-port-fr
      run: |
        $msmdsrvPorts = Get-Process -Name msmdsrv -ErrorAction SilentlyContinue | ForEach-Object {
          Get-NetTCPConnection -OwningProcess $_.Id | Select-Object LocalPort -Unique
        }

        if ($msmdsrvPorts) {
          foreach ($port in $msmdsrvPorts) {
            Write-Host "msmdsrv.exe is listening on port: $($port.LocalPort)"
          }
          # Assume there is only one instance for simplicity and set it as an environment variable
          echo "MSMDSRV_PORT=$($msmdsrvPorts[0].LocalPort)" >> $GITHUB_ENV
          echo "::set-output name=msmdsrv-port::$($msmdsrvPorts[0].LocalPort)"
        } else {
          Write-Host "No msmdsrv.exe process found."
        }
        
    - name: Process the first database on the instance in French
      run: |
        Import-Module SqlServer
        $port = "${{ steps.get-msmdsrv-port-fr.outputs.msmdsrv-port }}"
        $asInstance = "localhost:$port"
        $connectionString = "Data Source=localhost:$port;"
        # Invoke the command and expect the result to be in XML format
        $xmlResult = Invoke-ASCmd -ConnectionString $connectionString -Query "SELECT [CATALOG_NAME] FROM $SYSTEM.DBSCHEMA_CATALOGS"
        
        # Parse the XML result
        $xml = [xml]$xmlResult

        # Now extract the data you need from the XML
        # You need to adjust the XPath query according to the actual structure of the XML
        $dbName = $xml.Rowset.Row.CATALOG_NAME
        
        # Process the database
        Invoke-ASCmd -Server $asInstance -Query "{
          ""refresh"": {
            ""type"": ""full"",
            ""objects"": [
              {
                ""database"": ""$dbName""
              }
            ]
          }
        }"
        Start-Sleep -Seconds 60
       
        Write-Host "Database $dbName processed."

    - name: Run DAX query and output the result in French
      run: |
        Import-Module SqlServer
        $port = "${{ steps.get-msmdsrv-port-fr.outputs.msmdsrv-port }}"
        $asInstance = "localhost:$port"
        
        $daxResult = Invoke-ASCmd -Server $asInstance -Query "EVALUATE enumerations"
        Write-Host "DAX Query Result:"
        Write-Host $daxResult